version: "1"
services:
- type: web
  name: events-sync
  plan: free
  envVars:
  - key: CONFIG_ORGANIZATIONS_DALLAS_BICYCLE_COALITION_IMPORTER
    sync: false
  - key: CONFIG_ORGANIZATIONS_DALLAS_BICYCLE_COALITION_URL
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: DISCORD_REDIRECT_URI
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: DISCORD_CLIENT_SECRET
    sync: false
  - key: DISCORD_CLIENT_ID
    sync: false
  region: ohio
  dockerCommand: /root/bin/web 2>&1
  autoDeployTrigger: commit
  buildFilter:
    ignoredPaths:
    - static/*
  # # NEW RUNTIME
  runtime: image
  image:
    url: docker.io/domjdfw/events-sync:latest
  # # OLD RUNTIME
  # runtime: docker
  # repo: https://github.com/DallasUrbanists/events-sync
  # dockerContext: .
  # dockerfilePath: ./Dockerfile
  # registryCredential:
  #   fromRegistryCreds:
  #     name: dockerhub domjdfw
