name: Sync Calendar Events

on:
  schedule:
    # Run at midnight and noon UTC
    - cron: '0 0,12 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  sync-calendar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Fetch calendar data with retry
      id: fetch-calendar
      run: |
        import requests
        import time
        import sys

        url = "http://events-sync.onrender.com/ical"
        max_attempts = 30  # 5 minutes with 10-second intervals
        attempt = 0

        while attempt < max_attempts:
            try:
                print(f"Attempt {attempt + 1}/{max_attempts}: Fetching calendar data...")
                response = requests.get(url, timeout=30)
                response.raise_for_status()

                # Check if we got valid calendar data
                content = response.text
                if content.startswith('BEGIN:VCALENDAR') and content.endswith('END:VCALENDAR'):
                    print("✅ Successfully fetched calendar data")
                    with open('static/dallas-urbanists-events-v3.ics', 'w', encoding='utf-8') as f:
                        f.write(content)
                    break
                else:
                    print("❌ Response doesn't appear to be valid calendar data")
                    raise Exception("Invalid calendar data")

            except Exception as e:
                attempt += 1
                if attempt >= max_attempts:
                    print(f"❌ Failed to fetch calendar data after {max_attempts} attempts")
                    print(f"Last error: {e}")
                    sys.exit(1)

                print(f"⚠️ Attempt failed: {e}")
                print(f"Waiting 10 seconds before retry...")
                time.sleep(10)

    - name: Check for changes
      id: check-changes
      run: |
        if git diff --quiet static/dallas-urbanists-events-v3.ics; then
          echo "No changes detected"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.check-changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add static/dallas-urbanists-events-v3.ics
        git commit -m "Update calendar events [skip ci]"
        git push
