name: Sync Calendar Events

on:
  schedule:
    # Run at midnight and noon UTC
    - cron: '0 */1 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  sync-calendar:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch calendar data with retry
      id: fetch-calendar
      run: |
        for i in {1..5}; do
        echo "Attempt $i/5: Fetching calendar data..."

        if curl -f -s -o static/dallas-urbanists-events-v3.ics "https://events-sync.onrender.com/ical"; then
          if head -1 static/dallas-urbanists-events-v3.ics | grep -q "BEGIN:VCALENDAR" && tail -1 static/dallas-urbanists-events-v3.ics | grep -q "END:VCALENDAR"; then
            echo "✅ Successfully fetched calendar data"
            break
          else
            echo "❌ Response doesn't appear to be valid calendar data"
            if [ $i -eq 5 ]; then
              echo "❌ Failed to fetch valid calendar data after 5 attempts"
              exit 1
            fi
          fi
        else
          echo "⚠️ Attempt $i failed"
          if [ $i -eq 5 ]; then
            echo "❌ Failed to fetch calendar data after 5 attempts"
            exit 1
          fi
          echo "Waiting 10 seconds before retry..."
          sleep 10
        fi
        done

    - name: Check for changes
      id: check-changes
      run: |
        if git diff --quiet static/dallas-urbanists-events-v3.ics; then
          echo "No changes detected"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.check-changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add static/dallas-urbanists-events-v3.ics
        git commit -m "[skip render] Update calendar events"
        git push
